### ISSUE TITLE
Add Che/CRW to openshift-homeroom deployment

### ISSUE THREAD

**Issue by jharmison-redhat** [jharmison-redhat/openshift-devsecops#6]
Some JS tweaks will be necessary so we should base our OpenShift Homeroom installation on a fork we can modify.

**Comment by andykrohg** [comment]
I've started work on this:
https://github.com/andykrohg/workshop-dashboard.git
https://github.com/andykrohg/che-dashboard

https://quay.io/repository/akrohg/workshop-dashboard-crw
https://quay.io/repository/akrohg/che-dashboard

**Comment by andykrohg** [comment]
Ended up changing my approach for this one. I originally tried to bypass OAuth (what the main workshop-dashboard does for the console), but it became far too cumbersome trying to negotiate all that inside an iframe. 

Instead, I modified the terminal image so that it shares the Keycloak instance provisioned by the CRW operator (rather than OCP OAuth directly).

https://github.com/andykrohg/workshop-terminal
https://github.com/andykrohg/workshop-dashboard

https://quay.io/repository/akrohg/workshop-dashboard-crw
https://quay.io/repository/akrohg/workshop-terminal-keycloak

**Comment by andykrohg** [comment]
To see what this looks like, run the following steps:
1. Deploy Code Ready Workspaces using the operator
2. Login to Keycloak, and update the **codeready-public** Client in the **Codeready** realm to allow "*" for both Valid Redirect URI and Web Origins.
3. Run this command in the same project
`oc new-app https://raw.githubusercontent.com/andykrohg/workshop-dashboard/develop/templates/production-codeready.json -p OPENSHIFT_PROJECT=<your_project> -p CLUSTER_SUBDOMAIN=<your subdomain (apps.example.com)>`
